export let start_codon_options = [
		{
			author: 'n/a',
			categories: ['start-codon'],
			collectionId: '',
			description: 'Canonical E. coli start codon; highest initiation efficiency',
			id: '',
			notes: '',
			part_id: 0,
			part_name: 'ATG',
			part_type: 'Start Codon',
			sequence: 'ATG',
			sequence_length: 3,
			short_desc: 'Primary E. coli start codon (Met)',
			source: '',
			uses: 0
		},
		{
			author: 'n/a',
			categories: ['start-codon'],
			collectionId: '',
			description: 'Near-cognate start codon; ~10–20% efficiency of ATG',
			id: '',
			notes: '',
			part_id: 0,
			part_name: 'GTG',
			part_type: 'Start Codon',
			sequence: 'GTG',
			sequence_length: 3,
			short_desc: 'Weaker start codon (Val → Met at initiation)',
			source: '',
			uses: 0
		},
		{
			author: 'n/a',
			categories: ['start-codon'],
			collectionId: '',
			description: 'Near-cognate start codon; typically weaker than GTG',
			id: '',
			notes: '',
			part_id: 0,
			part_name: 'TTG',
			part_type: 'Start Codon',
			sequence: 'TTG',
			sequence_length: 3,
			short_desc: 'Weak start codon (Leu → Met at initiation)',
			source: '',
			uses: 0
		}
		]

export let stop_codon_options = [
		{
			'author': 'n/a',
			'categories': [ 'stop-codon' ],
			'collectionId': '',
			'description': 'Ochre stop codon, commonly used in E. coli',
			'id': '',
			'notes': '',
			'part_id': 0,
			'part_name': 'TAA',
			'part_type': 'Stop Codon',
			'sequence': 'TAA',
			'sequence_length': 3,
			'short_desc': 'Ochre stop codon, commonly used in E. coli',
			'source': '',
			'uses': 0
		},
		{
			'author': 'n/a',
			'categories': [ 'stop-codon' ],
			'collectionId': '',
			'description': 'Opal stop codon, rare in E. coli',
			'id': '',
			'notes': '',
			'part_id': 0,
			'part_name': 'TGA',
			'part_type': 'Stop Codon',
			'sequence': 'TGA',
			'sequence_length': 3,
			'short_desc': 'Opal stop codon, rare in E. coli',
			'source': '',
			'uses': 0
		},
		{
			'author': 'n/a',
			'categories': [ 'stop-codon' ],
			'collectionId': '',
			'description': 'Amber stop codon, less frequently used',
			'id': '',
			'notes': '',
			'part_id': 0,
			'part_name': 'TAG',
			'part_type': 'Stop Codon',
			'sequence': 'TAG',
			'sequence_length': 3,
			'short_desc': 'Amber stop codon, less frequently used',
			'source': '',
			'uses': 0
		},
		{
			'author': 'n/a',
			'categories': [ 'stop-codon' ],
			'collectionId': '',
			'description': 'Double stop codon (TAA + TGA), increases termination efficiency',
			'id': '',
			'notes': '',
			'part_id': 0,
			'part_name': 'TAATGA',
			'part_type': 'Stop Codon',
			'sequence': 'TAATGA',
			'sequence_length': 3,
			'short_desc': 'Double stop codon (TAA + TGA), increases termination efficiency',
			'source': '',
			'uses': 0
		},
		{
			'author': 'n/a',
			'categories': [ 'stop-codon' ],
			'collectionId': '',
			'description': 'Double stop codon (TAA + TAG), increases termination efficiency',
			'id': '',
			'notes': '',
			'part_id': 0,
			'part_name': 'TAATAG',
			'part_type': 'Stop Codon',
			'sequence': 'TAATAG',
			'sequence_length': 3,
			'short_desc': 'Double stop codon (TAA + TAG), increases termination efficiency',
			'source': '',
			'uses': 0
		}
		]