export let current_well_colors_import = {
    'White': true,
    'Erase': true,
    // Lab
    'sfGFP' : true,
    'mRFP1' : true,
    'mKO2' : true,
    'mKate2': true,
    'sfGFP_mKO2': true,
    // 'Azurite': false,
    // 'mTagBFP2': false,
    // 'mCerulean3': false,
    // 'mEGFP': false,
    // 'mClover3': false,
    // 'mNeonGreen': false,
    // 'mAzamiGreen': false,
    // 'mWatermelon': false,
    // 'mLychee': false,
    // 'mChartreuse': false,
    // Twist
    // 'avGFP': false,
    // 'DsRed': false,
    // 'eqFP578': false,
    // 'mTurquoise2': false,
    // 'mCitrine': false,
    // 'mVenus': false,
    // 'mCherry': false,
    // 'mHoneydew': false,
    // 'mBanana': false,
    // 'tdTomato': false,
    // 'mPlum': false,
    // 'TagRFP': false,
    // 'mRuby2': false,
    // 'Electra2': false,
    // 'mTFP1': false,
    // 'mWasabi': false,
    // 'mScarlet-I': false,
    // 'Ultramarine': false,
    // 'mPapaya': false,
    // 'ZsGreen1': false,
    // 'mMiCy': false,
    // 'mStayGold2': false,
}

export let well_colors = {
    // In Lab
    'sfGFP' : ' #00ff00',
    'mRFP1' : ' #fc0000',
    'mKO2' : ' #ff9c00',
    'mKate2': ' #9b0000',
    'sfGFP_mKO2': ' #fffb00',
    // 'Azurite': ' #0023ff',
    // 'mTagBFP2': ' #0047ff',
    // 'mCerulean3': ' #00b2ff',
    // 'mEGFP': ' #00ff26',
    // 'mClover3': ' #1dff00',
    // 'mNeonGreen': ' #19ff00',
    // 'mAzamiGreen': ' #00ff3f',
    // 'mWatermelon': ' #12ff00',
    // 'mLychee': ' #ff2300',
    // 'mChartreuse': ' #00ff00',
    'White': ' #ffffff',
    'Erase': ' #e5e5e5',
    // Twist
    // 'avGFP': ' #00ff0c',
    // 'DsRed': ' #ff5600',
    // 'eqFP578': ' #ff6900',
    // 'mTurquoise2': ' #00adff',
    // 'mCitrine': ' #d6ff00',
    // 'mVenus': ' #cfff00',
    // 'mCherry': ' #f70000',
    // 'mHoneydew': ' #ffa800',
    // 'mBanana': ' #ffcc00',
    // 'tdTomato': ' #ff5e00',
    // 'mPlum': ' #c00000',
    // 'TagRFP': ' #ff5200',
    // 'mRuby2': ' #ff1300',
    // 'Electra2': ' #0047ff',
    // 'mTFP1': ' #00ffe5',
    // 'mWasabi': ' #00ff0c',
    // 'mScarlet-I': ' #ff2f00',
    // 'Ultramarine': ' #e10000',
    // 'mPapaya': ' #fffb00',
    // 'ZsGreen1': ' #00ff3f',
    // 'mMiCy': ' #00ffb2',
    // 'mStayGold2': ' #00ff0c',
}

export const old_well_colors = {
    'Red' : '#fca5a5', // red-300
    'Green' : '#86efac', // green-300
    'Orange' : '#ffcc80', // orange-200
    'White': '#ffffff',
}