// Current available options
export let current_well_colors_import = {
    'White': true,
    'Erase': true,
    // Lab
    'sfGFP': true,
    'mRFP1': true,
    'mKO2': true,
    'mKate2': false,
    'EGFP': false,
    'Venus': true,
    'mRuby2': false,
    'TagBFP': false,
    'mKate2_TF': true,
    'mChartreuse_TF': false,
    'mLychee_TF': false,
    'Azurite': true,
    'mTagBFP2': false,
    'mCerulean3': true,
    'mEGFP': false,
    'mClover3': true,
    'mNeonGreen': false,
    'mAzamiGreen': false,
    'mWatermelon': false,
    'mJuniper': true,
    'avGFP': false,
    'DsRed': false,
    'eqFP578': false,
    'mTurquoise2': true,
    'mCitrine': false,
    'mVenus': false,
    'mCherry': false,
    'mHoneydew': false,
    'mBanana': true,
    'tdTomato': false,
    'mPlum': true,
    'TagRFP': false,
    'Electra2': true,
    'mTFP1': false,
    'mWasabi': true,
    'mScarlet_I': true,
    'Ultramarine': false,
    'mPapaya': true,
    'ZsGreen1': false,
    'mMiCy': false,
    'mStayGold2': false,
    'PA_GFP': false,
}

export let source_384_well_colors = {
    'sfgfp': 'A',
    'mrfp1': 'B',
    'mko2': 'C',
    'venus':'D',
    'mkate2_tf': 'E',
    'azurite': 'F',
    'mcerulean3': 'G',
    'mclover3': 'H',
    'mjuniper': 'I',
    'mturquoise2': 'J',
    'mbanana': 'K',
    'mplum': 'L',
    'electra2': 'M',
    'mwasabi': 'N',
    'mscarlet_i': 'O',
    'mpapaya': 'P',
}

// export let current_well_colors_import = {
//     'White': true,
//     'Erase': true,
//     // Lab
//     'sfGFP': true,
//     'mRFP1': true,
//     'mKO2': true,
//     'mKate2': true,
//     'EGFP': true,
//     'Venus': true,
//     'mRuby2': true,
//     'TagBFP': true,
//     'mKate2_TF': true,
//     'mChartreuse_TF': true,
//     'mLychee_TF': true,
//     'Azurite': true,
//     'mTagBFP2': true,
//     'mCerulean3': true,
//     'mEGFP': true,
//     'mClover3': true,
//     'mNeonGreen': true,
//     'mAzamiGreen': true,
//     'mWatermelon': true,
//     'mJuniper': true,
//     'avGFP': true,
//     'DsRed': true,
//     'eqFP578': true,
//     'mTurquoise2': true,
//     'mCitrine': true,
//     'mVenus': true,
//     'mCherry': true,
//     'mHoneydew': true,
//     'mBanana': true,
//     'tdTomato': true,
//     'mPlum': true,
//     'TagRFP': true,
//     'Electra2': true,
//     'mTFP1': true,
//     'mWasabi': true,
//     'mScarlet_I': true,
//     'Ultramarine': true,
//     'mPapaya': true,
//     'ZsGreen1': true,
//     'mMiCy': true,
//     'mStayGold2': true,
//     'PA_GFP': false,
// }

export let well_colors = {
    'sfGFP' : ' #00ff00',
    'mRFP1' : ' #fc0000',
    'mKO2' : ' #ff9c00',
    'mKate2': ' #9b0000',
    'EGFP': ' #00ff26',
    'mTurquoise2': ' #00adff',
    'Venus': ' #d3ff00',
    'mRuby2': ' #ff1300',
    'Azurite': ' #0023ff',
    'TagBFP': ' #0056ff',
    'mCherry': ' #f70000',
    'mKate2_TF': ' #9b0000',
    'mChartreuse_TF': ' #00ff00',
    'mLychee_TF': ' #ff2300',
    'mTagBFP2': ' #0047ff',
    'mTagBFP2': ' #0047ff',
    'mCerulean3': ' #00b2ff',
    'mEGFP': ' #00ff26',
    'mClover3': ' #1dff00',
    'mNeonGreen': ' #19ff00',
    'mAzamiGreen': ' #00ff3f',
    'mWatermelon': ' #12ff00',
    'mJuniper': ' #00b2ff',
    'avGFP': ' #00ff0c',
    'DsRed': ' #ff5600',
    'eqFP578': ' #ff6900',
    'mCitrine': ' #d6ff00',
    'mVenus': ' #cfff00',
    'mHoneydew': ' #ffa800',
    'mBanana': ' #ffcc00',
    'tdTomato': ' #ff5e00',
    'mPlum': ' #c00000',
    'TagRFP': ' #ff5200',
    'Electra2': ' #0047ff',
    'mTFP1': ' #00ffe5',
    'mWasabi': ' #00ff0c',
    'mScarlet_I': ' #ff2f00',
    'Ultramarine': ' #e10000',
    'mPapaya': ' #fffb00',
    'ZsGreen1': ' #00ff3f',
    'mMiCy': ' #00ffb2',
    'mStayGold2': ' #00ff0c',
    'PA_GFP': ' #00ff0c',
    'White': ' #ffffff',
    'Erase': ' #e5e5e5',
}

export const old_well_colors = {
    'sfGFP_mKO2': '#ffd000', // yellow-200
    'Red' : '#fca5a5', // red-300
    'Green' : '#86efac', // green-300
    'Orange' : '#ffcc80', // orange-200
    'White': '#ffffff',
}